#!/bin/sh -x
#
# Entrypoint script for docker image of GeminiStack
#
#dpkg-divert --local --rename --add /sbin/initctl
ln -sf /bin/true /sbin/initctl
# sysctl -w kernel.shmmax=17179869184
# Make file changes to run postgresql in less memory
cp postgresql.rb /opt/chef-server/embedded/cookbooks/chef-server/recipes/postgresql.rb
if [ -z "$UPGRADE" ]
then
	export UPGRADE=0
else
	export UPGRADE=$UPGRADE
fi
 
# Now start Chef Server
/opt/chef-server/embedded/bin/runsvdir-start &
#UPGRADE value that is significant
# UPGRADE = 0 or 1 - Clean Install
# UPGRADE = 2 - Upgrade Chef.
if [ "$UPGRADE" == 2  || ! -f /etc/chef-server/admin.pem ] 
then
    cp -pa /var/opt/chef-server/*.json /etc/chef-server/
    cp -pa /var/opt/chef-server/*.pem  /etc/chef-server/
fi
chef-server-ctl reconfigure
# After Reconfigure , it would have started the chef-solo, postgres and nginx 
# and have generated the pem files if not present. To hanlde upgrade, we need to reconfigure
# Using the same set of pem files generated by the previous Installation.
# Hence copy the pem files along with "permissions" to a vol mount location 
# Then copy back before you start the reconfiguration.

cp -pa /etc/chef-server/*.json /var/opt/chef-server/
cp -pa /etc/chef-server/*.pem /var/opt/chef-server/ 

tail -F /var/log/*.log &
chef-server-ctl tail
